name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - name: Install dependencies (root + workspaces)
        run: npm ci --ignore-scripts --workspaces --include-workspace-root

      - name: Prisma generate
        working-directory: server
        run: npx prisma generate

      - name: Prisma migrate (CI DB)
        working-directory: server
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
        run: npx prisma migrate deploy

      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck

      - name: Test (server)
        working-directory: server
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          JWT_SECRET: test_secret
        run: npm run test --silent

      - name: Build client
        working-directory: client
        run: npm run build
